import React, { useState, useEffect } from 'react';
import { KeyRound, ShieldAlert, ArrowRight, Loader2, AlertCircle, QrCode, Copy, Check } from 'lucide-react';
import { useAdminAuth } from '../context/AdminAuthContext';

export const MfaChallengeModal: React.FC = () => {
  const { isMfaRequired, isMfaEnrollmentRequired, mfaFactors, verifyMfaTotp, enrollMfaTotp, signOut } = useAdminAuth();
  const [totpCode, setTotpCode] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);
  const [isLoadingEnrollment, setIsLoadingEnrollment] = useState(false);
  const [enrollmentData, setEnrollmentData] = useState<{ factorId: string; secret: string; qrCode?: string; uri?: string } | null>(null);
  const [copiedSecret, setCopiedSecret] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // When enrollment is required, automatically initiate enrollment session
  useEffect(() => {
    if (isMfaRequired && isMfaEnrollmentRequired && !enrollmentData) {
      setIsLoadingEnrollment(true);
      setErrorMsg(null);
      enrollMfaTotp().then((res) => {
        setIsLoadingEnrollment(false);
        if (res.success && res.factorId) {
          setEnrollmentData({
            factorId: res.factorId,
            secret: res.totp?.secret || '',
            qrCode: res.totp?.qr_code || '',
            uri: res.totp?.uri || '',
          });
        } else {
          setErrorMsg(res.error || 'Failed to initialize MFA enrollment. Please try again.');
        }
      });
    }
  }, [isMfaRequired, isMfaEnrollmentRequired, enrollMfaTotp, enrollmentData]);

  if (!isMfaRequired) return null;

  const currentFactorId = enrollmentData?.factorId || mfaFactors[0]?.id || 'factor-default';

  const handleCopySecret = () => {
    if (enrollmentData?.secret) {
      navigator.clipboard.writeText(enrollmentData.secret);
      setCopiedSecret(true);
      setTimeout(() => setCopiedSecret(false), 2000);
    }
  };

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    const cleanCode = totpCode.trim().replace(/\s+/g, '');
    if (cleanCode.length !== 6) {
      setErrorMsg('Please enter a 6-digit verification code.');
      return;
    }

    setIsVerifying(true);
    setErrorMsg(null);

    const result = await verifyMfaTotp(currentFactorId, cleanCode);
    setIsVerifying(false);

    if (!result.success) {
      setErrorMsg(result.error || 'Invalid two-factor code. Please check your authenticator app.');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="w-full max-w-md bg-[#07383D] border border-[#166D74] rounded-2xl p-6 sm:p-8 shadow-2xl relative">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-12 h-12 rounded-xl bg-[#14BEB8]/15 border border-[#14BEB8]/30 flex items-center justify-center text-[#14BEB8]">
            {isMfaEnrollmentRequired ? <QrCode className="w-6 h-6" /> : <KeyRound className="w-6 h-6" />}
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">
              {isMfaEnrollmentRequired ? 'Two-Factor Enrollment Required' : 'Two-Factor Challenge'}
            </h3>
            <p className="text-xs text-[#8EACB0]">
              {isMfaEnrollmentRequired ? 'Mandatory Admin Account Setup' : 'Supabase Multi-Factor Authentication'}
            </p>
          </div>
        </div>

        <p className="text-xs text-[#C2D7D9] leading-relaxed mb-4">
          {isMfaEnrollmentRequired
            ? 'Administrator security policy strictly mandates Authenticator Assurance Level 2 (AAL2). Scan the QR code or enter the secret key into Google Authenticator, 1Password, or Authy to enroll.'
            : 'Admin access requires hardware or app-based TOTP verification. Enter the 6-digit security code generated by your authenticator app.'}
        </p>

        {errorMsg && (
          <div className="mb-4 p-3 rounded-xl bg-red-500/10 border border-red-500/30 flex items-start gap-2.5 text-red-200 text-xs">
            <AlertCircle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
            <span>{errorMsg}</span>
          </div>
        )}

        {isMfaEnrollmentRequired && (
          <div className="mb-5 p-4 rounded-xl bg-[#052427] border border-[#166D74]">
            {isLoadingEnrollment ? (
              <div className="flex items-center justify-center py-6 gap-2 text-xs text-[#8EACB0]">
                <Loader2 className="w-4 h-4 animate-spin text-[#14BEB8]" />
                <span>Generating secure TOTP secret key...</span>
              </div>
            ) : enrollmentData ? (
              <div className="space-y-3">
                {enrollmentData.qrCode && (
                  <div className="flex justify-center p-3 bg-white rounded-xl mx-auto w-fit">
                    <img
                      src={enrollmentData.qrCode.startsWith('data:') ? enrollmentData.qrCode : `data:image/svg+xml;utf8,${encodeURIComponent(enrollmentData.qrCode)}`}
                      alt="TOTP QR Code"
                      className="w-36 h-36"
                    />
                  </div>
                )}
                <div>
                  <div className="text-[11px] uppercase tracking-wider text-[#8EACB0] font-semibold mb-1">
                    Manual Setup Secret Key
                  </div>
                  <div className="flex items-center justify-between bg-[#07383D] border border-[#166D74] rounded-lg px-3 py-2 text-xs font-mono text-[#14BEB8]">
                    <span className="truncate select-all">{enrollmentData.secret}</span>
                    <button
                      type="button"
                      onClick={handleCopySecret}
                      className="ml-2 p-1 hover:bg-[#0B4A50] rounded text-[#8EACB0] hover:text-white transition-colors cursor-pointer"
                      title="Copy Secret"
                    >
                      {copiedSecret ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        )}

        <form onSubmit={handleVerify} className="space-y-4">
          <div>
            <label className="block text-xs font-semibold text-[#8EACB0] uppercase tracking-wider mb-2">
              {isMfaEnrollmentRequired ? 'Enter 6-Digit Code from App to Confirm' : '6-Digit Authenticator Code'}
            </label>
            <input
              type="text"
              inputMode="numeric"
              pattern="[0-9]*"
              maxLength={6}
              autoFocus
              value={totpCode}
              onChange={(e) => setTotpCode(e.target.value.replace(/[^0-9]/g, ''))}
              placeholder="000000"
              className="w-full bg-[#052427] border border-[#166D74] focus:border-[#14BEB8] rounded-xl px-4 py-3 text-center text-2xl font-mono tracking-widest text-white placeholder-[#5D7A7D] outline-none"
            />
          </div>

          <div className="flex items-center gap-3 pt-2">
            <button
              type="button"
              onClick={() => signOut('manual')}
              className="flex-1 px-4 py-2.5 rounded-xl border border-[#166D74] hover:bg-[#0B4A50] text-xs font-semibold text-[#C2D7D9] transition-colors cursor-pointer"
            >
              Sign Out
            </button>
            <button
              type="submit"
              disabled={isVerifying || totpCode.length !== 6 || (isMfaEnrollmentRequired && !enrollmentData)}
              className="flex-1 bg-gradient-to-r from-[#006B70] to-[#14BEB8] hover:from-[#005B60] hover:to-[#10ABA5] text-[#052427] font-bold py-2.5 px-4 rounded-xl transition-all shadow-md flex items-center justify-center gap-2 text-xs disabled:opacity-50 cursor-pointer"
            >
              {isVerifying ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>Verifying...</span>
                </>
              ) : (
                <>
                  <span>{isMfaEnrollmentRequired ? 'Confirm & Activate' : 'Verify TOTP'}</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </>
              )}
            </button>
          </div>
        </form>

        <div className="mt-6 pt-4 border-t border-[#166D74]/40 flex items-center justify-between text-[11px] text-[#5D7A7D]">
          <span className="flex items-center gap-1">
            <ShieldAlert className="w-3 h-3 text-[#FFA987]" />
            Strict AAL2 Enforcement
          </span>
          <span>OFIS Control</span>
        </div>
      </div>
    </div>
  );
};
