import { Space, UserProfile, SearchFilters, Review } from './types';

export const INITIAL_USER: UserProfile = {
  id: 'user-001',
  name: 'Babatunde Adeyemi',
  email: 'tunde.adeyemi@paystack.com',
  phone: '+234 802 345 6789',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  role: 'user',
  isEmailVerified: true,
  emailVerifiedAt: '2024-01-15T11:00:00Z',
  company: 'Fintech Systems Ltd',
  bio: 'Software engineer and tech founder based in Lagos. Frequently booking focus desks and meeting pods.',
  walletBalanceNgn: 85000,
  savedSpaceIds: ['space-vi-hive', 'space-ikoyi-glass'],
  createdAt: '2024-01-15T10:30:00Z',
};

export const INITIAL_HOST: UserProfile = {
  id: 'host-001',
  name: 'Funke Akindele-Cole',
  email: 'funke@creativespace.ng',
  phone: '+234 803 987 6543',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
  role: 'host',
  isEmailVerified: true,
  emailVerifiedAt: '2023-08-10T12:30:00Z',
  company: 'OFIS Premier Workspaces',
  bio: 'Hospitality & commercial real estate manager operating 4 serviced hubs across Victoria Island and Ikoyi.',
  walletBalanceNgn: 420000,
  savedSpaceIds: [],
  createdAt: '2023-08-10T12:00:00Z',
};

export const GUEST_USER: UserProfile = {
  id: 'guest-user',
  name: 'Guest Explorer',
  email: 'guest@ofis.ng',
  phone: '+234 800 000 0000',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80',
  role: 'user',
  isEmailVerified: false,
  company: 'Independent Professional',
  bio: 'Exploring workspaces and focus hubs.',
  walletBalanceNgn: 0,
  savedSpaceIds: [],
  createdAt: '2024-01-01T00:00:00Z',
};

export const POPULAR_CITIES = [
  'Lagos',
  'Abuja',
  'Port Harcourt',
  'Ibadan',
  'Enugu',
  'Accra',
  'Nairobi',
  'Kigali',
];

export const CATEGORY_METADATA = [
  {
    id: 'all',
    label: 'All Spaces',
    description: 'Explore entire physical space network (200 curated hubs)',
    icon: 'Sparkles',
    count: 200,
  },
  {
    id: 'coworking',
    label: 'Coworking & Desks',
    description: 'Hot desks, ergonomic seating & quiet booths',
    icon: 'Laptop',
    count: 58,
  },
  {
    id: 'meeting-room',
    label: 'Meeting Rooms',
    description: 'AV conferencing, 4K displays & boardroom suites',
    icon: 'Presentation',
    count: 45,
  },
  {
    id: 'private-office',
    label: 'Private Offices',
    description: 'Enclosed suites for teams & executive privacy',
    icon: 'Building2',
    count: 35,
  },
  {
    id: 'training-room',
    label: 'Training Rooms',
    description: 'Classroom layouts, dual projectors & workshop setups',
    icon: 'GraduationCap',
    count: 22,
  },
  {
    id: 'event-space',
    label: 'Event Spaces',
    description: 'Keynotes, tech meetups, demos & corporate mixers',
    icon: 'Users',
    count: 18,
  },
  {
    id: 'studio',
    label: 'Studios (Audio/Photo)',
    description: 'Podcast suites, soundproof booths & cyclorama sets',
    icon: 'Camera',
    count: 14,
  },
  {
    id: 'other',
    label: 'Creative & Other',
    description: 'Rooftops, garden lounges & bespoke lofts',
    icon: 'Sparkles',
    count: 8,
  },
];

export const MOCK_SPACES: Space[] = [];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-001',
    spaceId: 'space-vi-hive',
    userId: 'user-002',
    userName: 'Kolawole Daniel',
    userRole: 'Senior Frontend Engineer @ Mono',
    rating: 5,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 4.8,
    cleanlinessRating: 5,
    valueRating: 4.9,
    comment: 'The power stability here is rock solid. Even during heavy grid outages in VI, the solar-gen auto-switch happened seamlessly without dropping my video call with London. Internet speeds tested at 295Mbps. Espresso bar on the 2nd floor is a huge bonus.',
    visitDate: 'Visited 4 days ago • Hot Desk Full Day',
    helpfulCount: 18,
    isHelpfulByUser: false,
    verifiedAmenities: ['24/7 Power', 'Starlink 500Mbps', 'Espresso Bar', 'Herman Miller Chair'],
    photos: [
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-10T14:32:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-002',
    spaceId: 'space-vi-hive',
    userId: 'user-003',
    userName: 'Zainab Mohammed',
    userRole: 'Lead Product Designer @ Paystack',
    rating: 5,
    powerRating: 5,
    internetRating: 4.9,
    noiseRating: 5,
    cleanlinessRating: 5,
    valueRating: 4.8,
    comment: 'Herman Miller Aeron chairs are genuinely ergonomic for 10-hour sprint days. The acoustic phone booths are super quiet for user testing calls. Super clean restrooms and great coffee.',
    visitDate: 'Visited last week • Dedicated Desk',
    helpfulCount: 12,
    isHelpfulByUser: false,
    verifiedAmenities: ['Acoustic Phone Booth', 'Ergonomic Task Chairs', 'Espresso Bar'],
    photos: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-01-28T09:15:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-003',
    spaceId: 'space-vi-hive',
    userId: 'user-005',
    userName: 'Emeka Nwosu',
    userRole: 'Tech Founder & CTO',
    rating: 4.8,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 4.6,
    cleanlinessRating: 4.9,
    valueRating: 4.7,
    comment: 'Booked a hot desk for my distributed team sprint. The Starlink + MainOne fiber dual link is ridiculously fast (sub-10ms ping to AWS EU-West). Zero latency on pair programming sessions.',
    visitDate: 'Visited 2 weeks ago • Hot Desk Pass',
    helpfulCount: 9,
    isHelpfulByUser: false,
    verifiedAmenities: ['Dual Fiber + Starlink', 'Dual Genset', 'Free Parking'],
    createdAt: '2025-01-18T11:20:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-004',
    spaceId: 'space-ikoyi-boardroom',
    userId: 'user-004',
    userName: 'Dr. Segun Adeleke',
    userRole: 'Managing Partner, Ventures Capital',
    rating: 5,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 5,
    cleanlinessRating: 5,
    valueRating: 5,
    comment: 'Impeccable boardroom setup. Our international investors connected via Polycom 4K and commented on how crystal clear the audio was. The hospitality staff served fresh refreshments during the pitch session.',
    visitDate: 'Visited Feb 14, 2025 • Executive Boardroom (4 hrs)',
    helpfulCount: 15,
    isHelpfulByUser: false,
    verifiedAmenities: ['Polycom 4K Conferencing', 'Motorized Blackout Blinds', 'Executive Barista'],
    photos: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-14T16:00:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-005',
    spaceId: 'space-ikoyi-glass',
    userId: 'user-006',
    userName: 'Amina Bello',
    userRole: 'Country Director, Global NGO',
    rating: 5,
    powerRating: 5,
    internetRating: 4.8,
    noiseRating: 4.9,
    cleanlinessRating: 5,
    valueRating: 4.9,
    comment: 'Spectacular glass facade with panoramic views of Lagos lagoon. Natural daylight is amazing for productivity. Ultra secure with turnstile biometric entry.',
    visitDate: 'Visited 5 days ago • Executive Private Suite',
    helpfulCount: 11,
    isHelpfulByUser: false,
    verifiedAmenities: ['Lagoon View', '24/7 Security', 'Biometric QR Access'],
    photos: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-18T10:00:00Z',
    verifiedBooking: true,
  },
  {
    id: 'rev-006',
    spaceId: 'space-lekki-podcast',
    userId: 'user-007',
    userName: 'Tariq Al-Hassan',
    userRole: 'Creator & Host, The Africa Tech Narrative',
    rating: 5,
    powerRating: 5,
    internetRating: 5,
    noiseRating: 5,
    cleanlinessRating: 5,
    valueRating: 5,
    comment: 'The acoustic dampening here is broadcast studio grade (-60dB floor). Shure SM7B mics with Rodecaster Pro II made our 3-hour recording effortless. Highly recommend the on-site sound engineer!',
    visitDate: 'Visited 1 week ago • 3hr Recording Session',
    helpfulCount: 14,
    isHelpfulByUser: false,
    verifiedAmenities: ['Shure SM7B Mics', 'Rodecaster Pro II', 'Acoustic Soundproofing'],
    photos: [
      'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80'
    ],
    createdAt: '2025-02-08T18:30:00Z',
    verifiedBooking: true,
  }
];
